package accessModifier;

 class DefaultClass {

	//DISSCUSSION OF DEFAULT ACCESS MODOFIER
	
	// TO MAKE THE CLASS AS DEFAULT REMOVE THE "PUBLIC" KEYWORD ROM THE CLASS
	// WHEN THE CLASS IS DECLARED AS DEFAULT IT IS ACCESSIBLE ONLY INSIDE THE PACKAGE AND NOT OUTSIDE THE PACKAGE
	
	// WHEN WE HAVE TO ACCESS THE CLASS INSIDE THE PACAKAGE AND WE DONT HAVE TO MAKE THE CHILDCLASS OF IT AT SUCH TIME WE USE SYNTAX LIKE---> CLASS FINAL CLASSNAME
	
	
	public void m2() 
	{
	System.out.println("m2 from the default class");	
	}
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
}
